# Generated by Django 5.2.5 on 2025-08-15 19:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Categorías',
            },
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Proveedores',
            },
        ),
        migrations.CreateModel(
            name='Subcategoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategorias', to='precios.categoria')),
            ],
            options={
                'verbose_name_plural': 'Subcategorías',
                'unique_together': {('categoria', 'nombre')},
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('tipo_compra', models.CharField(choices=[('U', 'Unidad'), ('C', 'Caja'), ('B', 'Bolsa')], max_length=1)),
                ('unidades_por_paquete', models.PositiveIntegerField(blank=True, help_text='Cantidad de unidades por caja/bolsa', null=True)),
                ('precio_compra_paquete', models.DecimalField(decimal_places=2, help_text='Precio de compra del paquete/caja/unidad', max_digits=10)),
                ('descuento_compra', models.DecimalField(decimal_places=2, default=0, help_text='Porcentaje de descuento en la compra', max_digits=5)),
                ('precio_compra_unitario', models.DecimalField(decimal_places=2, editable=False, help_text='Precio de compra por unidad (calculado)', max_digits=10)),
                ('tipo_venta', models.CharField(choices=[('U', 'Unidad'), ('P', 'Promoción')], max_length=1)),
                ('margen_ganancia', models.DecimalField(decimal_places=2, help_text='Porcentaje de ganancia sugerido', max_digits=5)),
                ('precio_venta_sugerido', models.DecimalField(decimal_places=2, editable=False, max_digits=10)),
                ('precio_venta_final', models.DecimalField(decimal_places=2, help_text='Precio final de venta al público', max_digits=10)),
                ('fecha_ultima_compra', models.DateTimeField(auto_now=True)),
                ('activo', models.BooleanField(default=True)),
                ('proveedor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='productos', to='precios.proveedor')),
                ('subcategoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos', to='precios.subcategoria')),
            ],
            options={
                'verbose_name_plural': 'Productos',
                'ordering': ['nombre'],
            },
        ),
    ]
