# Generated by Django 5.2.5 on 2025-08-16 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('precios', '0002_marca_producto_marca'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='alerta_stock',
            field=models.BooleanField(default=False, help_text='Indica si se debe alertar cuando el stock está bajo'),
        ),
        migrations.AddField(
            model_name='producto',
            name='cantidad_stock',
            field=models.PositiveIntegerField(default=0, help_text='Cantidad actual en stock'),
        ),
        migrations.AddField(
            model_name='producto',
            name='stock_minimo',
            field=models.PositiveIntegerField(default=1, help_text='Cantidad mínima antes de necesitar reposición'),
        ),
    ]
