# Generated by Django 5.2.5 on 2025-08-16 21:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('precios', '0004_movimientostock'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movimientostock',
            options={'ordering': ['-fecha']},
        ),
        migrations.RemoveField(
            model_name='movimientostock',
            name='precio_unitario',
        ),
    ]
