# Generated by Django 5.2.5 on 2025-08-16 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('precios', '0005_alter_movimientostock_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movimientostock',
            name='usuario',
        ),
    ]
