# Generated by Django 5.2.5 on 2025-09-06 04:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('precios', '0007_alter_proveedor_options_remove_proveedor_activo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistorialPrecio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio_anterior', models.DecimalField(decimal_places=2, help_text='Precio anterior al cambio', max_digits=10)),
                ('precio_nuevo', models.DecimalField(decimal_places=2, help_text='Nuevo precio después del cambio', max_digits=10)),
                ('fecha_cambio', models.DateTimeField(auto_now_add=True)),
                ('motivo', models.CharField(blank=True, help_text='Razón del cambio de precio', max_length=255)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_precios', to='precios.producto')),
            ],
            options={
                'verbose_name': 'Historial de Precio',
                'verbose_name_plural': 'Historial de Precios',
                'ordering': ['-fecha_cambio'],
            },
        ),
    ]
