# Generated by Django 5.2.5 on 2025-09-06 05:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('precios', '0009_producto_fecha_creacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventoProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_evento', models.CharField(choices=[('CREACION', 'Creación del producto'), ('MODIFICACION_PRECIO', 'Modificación de precio'), ('ACTIVACION', 'Activación del producto'), ('DESACTIVACION', 'Desactivación del producto'), ('ACTUALIZACION_STOCK', 'Actualización de stock'), ('CAMBIO_INFO', 'Cambio de información general')], help_text='Tipo de evento registrado', max_length=20)),
                ('fecha_evento', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora del evento')),
                ('descripcion', models.TextField(blank=True, help_text='Descripción detallada del evento')),
                ('valor_anterior', models.TextField(blank=True, help_text='Valor anterior (en formato JSON si es complejo)', null=True)),
                ('valor_nuevo', models.TextField(blank=True, help_text='Nuevo valor (en formato JSON si es complejo)', null=True)),
                ('usuario', models.CharField(blank=True, help_text='Usuario que realizó el cambio', max_length=100)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to='precios.producto')),
            ],
            options={
                'verbose_name': 'Evento de Producto',
                'verbose_name_plural': 'Eventos de Productos',
                'ordering': ['-fecha_evento'],
                'indexes': [models.Index(fields=['producto', 'tipo_evento'], name='precios_eve_product_c1c15c_idx'), models.Index(fields=['fecha_evento'], name='precios_eve_fecha_e_764731_idx'), models.Index(fields=['tipo_evento'], name='precios_eve_tipo_ev_fe08e0_idx')],
            },
        ),
    ]
