# Generated by Django 5.2.5 on 2025-09-07 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('precios', '0010_eventoproducto'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='producto',
            index=models.Index(fields=['nombre'], name='producto_nombre_idx'),
        ),
        migrations.AddIndex(
            model_name='producto',
            index=models.Index(fields=['precio_venta_final'], name='producto_precio_idx'),
        ),
        migrations.AddIndex(
            model_name='producto',
            index=models.Index(fields=['cantidad_stock'], name='producto_stock_idx'),
        ),
        migrations.AddIndex(
            model_name='producto',
            index=models.Index(fields=['fecha_creacion'], name='producto_fecha_idx'),
        ),
        migrations.AddIndex(
            model_name='producto',
            index=models.Index(fields=['subcategoria', 'activo'], name='producto_cat_activo_idx'),
        ),
        migrations.AddIndex(
            model_name='producto',
            index=models.Index(fields=['proveedor', 'activo'], name='producto_prov_activo_idx'),
        ),
        migrations.AddIndex(
            model_name='producto',
            index=models.Index(fields=['alerta_stock'], name='producto_alerta_idx'),
        ),
        migrations.AddIndex(
            model_name='producto',
            index=models.Index(fields=['activo', 'cantidad_stock'], name='producto_estado_stock_idx'),
        ),
    ]
