# Generated by Django 5.2.5 on 2025-08-17 04:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('caja', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cajadiaria',
            name='descripcion_evento',
        ),
        migrations.RemoveField(
            model_name='cajadiaria',
            name='tiene_evento_especial',
        ),
    ]
