# Generated by Django 5.2.5 on 2025-08-17 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caja', '0002_remove_cajadiaria_descripcion_evento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventoespecial',
            name='descripcion',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
