# Generated by Django 5.2.5 on 2025-08-18 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caja', '0003_eventoespecial_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cajadiaria',
            name='saldo_inicial',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
