# Generated by Django 5.2.5 on 2025-08-21 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caja', '0004_alter_cajadiaria_saldo_inicial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cajadiaria',
            name='es_extra',
            field=models.BooleanField(default=False),
        ),
    ]
