# Generated by Django 5.2.5 on 2025-08-21 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('caja', '0005_cajadiaria_es_extra'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cajadiaria',
            unique_together={('fecha', 'turno', 'nivel', 'es_extra')},
        ),
    ]
