# Generated by Django 5.2.5 on 2025-08-22 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caja', '0006_alter_cajadiaria_unique_together'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='cajadiaria',
            constraint=models.UniqueConstraint(condition=models.Q(('cerrada', False)), fields=('nivel', 'turno'), name='unique_open_caja_nivel_turno'),
        ),
    ]
