# Generated by Django 5.2.5 on 2025-09-04 04:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caja', '0007_cajadiaria_unique_open_caja_nivel_turno'),
        ('precios', '0007_alter_proveedor_options_remove_proveedor_activo_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SaldoElectronico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('ultima_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Saldo Electrónico',
                'verbose_name_plural': 'Saldos Electrónicos',
            },
        ),
        migrations.CreateModel(
            name='CajaElectronica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('saldo_inicial', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('saldo_parcial', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('cerrada', models.BooleanField(default=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('usuario_responsable', models.ForeignKey(help_text='Usuario responsable de esta caja electrónica', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Caja Electrónica',
                'verbose_name_plural': 'Cajas Electrónicas',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='IngresoElectronico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(help_text='Descripción de la transferencia', max_length=255)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('caja_electronica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='caja.cajaelectronica')),
                ('usuario_registro', models.ForeignKey(help_text='Usuario que registró el ingreso', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ingreso Electrónico',
                'verbose_name_plural': 'Ingresos Electrónicos',
                'ordering': ['-fecha_registro'],
            },
        ),
        migrations.CreateModel(
            name='PagoElectronico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('comprobante', models.CharField(help_text='Número de comprobante o referencia', max_length=50)),
                ('observacion', models.TextField(blank=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('caja_electronica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='caja.cajaelectronica')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='precios.proveedor')),
                ('usuario_registro', models.ForeignKey(help_text='Usuario que registró el pago', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pago Electrónico',
                'verbose_name_plural': 'Pagos Electrónicos',
                'ordering': ['-fecha_registro'],
            },
        ),
        migrations.AddConstraint(
            model_name='cajaelectronica',
            constraint=models.UniqueConstraint(condition=models.Q(('cerrada', False)), fields=('cerrada',), name='unique_open_electronica_constraint'),
        ),
        migrations.AlterUniqueTogether(
            name='cajaelectronica',
            unique_together={('fecha',)},
        ),
    ]
