# Generated by Django 5.2.5 on 2025-09-05 12:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caja', '0008_saldoelectronico_cajaelectronica_ingresoelectronico_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cajadiaria',
            name='fecha_reapertura',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cajadiaria',
            name='fue_reabierta',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cajadiaria',
            name='usuario_reapertura',
            field=models.ForeignKey(blank=True, help_text='Usuario que reabrió esta caja', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cajas_reabiertas', to=settings.AUTH_USER_MODEL),
        ),
    ]
