# Generated by Django 5.2.5 on 2025-10-23 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caja', '0009_cajadiaria_fecha_reapertura_cajadiaria_fue_reabierta_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cajadiaria',
            name='diferencia_al_cerrar',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Diferencia exacta aplicada al saldo general cuando se cerró la caja', max_digits=10, null=True),
        ),
    ]
